### ISSUE TITLE
ctlptl not deleting kind registry

### ISSUE THREAD

**Issue by djcp** [tilt-dev/ctlptl#103]
I have these scripts:

### setup-cluster.sh
```
#!/usr/bin/env bash

cat <<EOF | ctlptl apply -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
EOF
```
and

### teardown-cluster.sh
```
#!/usr/bin/env bash

cat <<EOF | ctlptl delete -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
EOF
```

The setup script works fine and creates the kind backplane with a registry.

However, when I run the `teardown` script, the registry is left as an orphaned docker resource. I can get rid of this manually with some scripting, but I would've expected the `ctlptl delete` with the registry config to do that automatically.

**Comment by nicks** [comment]
It should work if you explicitly delete the registry in the teardown like:

```
cat <<EOF | ctlptl delete -f -
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
---
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
EOF
```

Here's the background: If you create a cluster that references a registry that doesn't exist, ctlptl will make a best-effort to create a registry for you. It makes the onboarding/ergonomics a bit simpler.

The downside of this approach is that create and delete are no longer inverses (since people need to be able to delete and re-create a cluster without wiping out the registry)

Not sure what the right answer is here. Possible solutions:
- A message that tells you the registry is still up, and how to delete it
- A flag to delete to also delete any implicitly created resources
- something else?

**Comment by djcp** [comment]
Or perhaps refactoring the creation process to make it more obvious that the registry is a separate thing that's created? I like the flag idea too, especially if you could pass it in during creation.
