### ISSUE TITLE
e2e not running with current kind master

### ISSUE THREAD

**Issue by chrislovecnm** [tilt-dev/ctlptl#116]
I am having problems with connecting to the registry so I ran the e2e tests to validate my environment.

```bash
# clove @ DESKTOP-6TGAFKG in ~/Workspace/src/github.com/tilt-dev/ctlptl/test/kind-cluster-network on git:main x [14:56:08]
$ ./e2e.sh
+++ realpath ./e2e.sh
++ dirname /home/clove/Workspace/src/github.com/tilt-dev/ctlptl/test/kind-cluster-network/e2e.sh
+ cd /home/clove/Workspace/src/github.com/tilt-dev/ctlptl/test/kind-cluster-network
+ ctlptl apply -f registry.yaml
Creating registry "ctlptl-test-registry"...
 🎮 Env DOCKER_HOST set. Assuming remote Docker and forwarding registry to localhost:5005
registry.ctlptl.dev/ctlptl-test-registry created
+ ctlptl apply -f cluster.yaml
creating cluster: No available kindest/node versions for kind version v0.12.0-alpha+31d33511ae0a86.
Please file an issue: https://github.com/tilt-dev/ctlptl/issues/new
```

I installed ctlptl from master and kind from master @ 31d33511ae0a86f04e5bd475acc422407349122c

And I am on wls2

**Comment by chrislovecnm** [comment]
I got past this error by using kind v0.11.0

**Comment by nicks** [comment]
This might be expected behavior. Here's the problem:

Your cluster.yaml has a kubernetesVersion in it.

When Kind does a release, they do official Kubernetes image releases (these are called kindest/node images). ctlptl looks up these releases to figure out which one to use.

If you're trying to use ctlptl with a dev version of Kind and a specific Kubernetes version, then there are no official images, so it simply doesn't know how to get a Kubernetes image for that version.

What do you think it should do in this case?

**Comment by nicks** [comment]
(one possibility is that Tilt should notice if you're using an alpha version of Kind, and ignore the kubernetesVersion field)

**Comment by chrislovecnm** [comment]
> What do you think it should do in this case?

If we really want to make it cool, run `kind version`, and if it is an unsupported version of kind throw an error.
