### ISSUE TITLE
Missing newline character with get cluster and template

### ISSUE THREAD

**Issue by chrislovecnm** [tilt-dev/ctlptl#123]
```bash
DOCKER_HOST=$(ctlptl get cluster kind-kind -o template --template '{{.status.localRegistryHosting.host}}')
echo ${DOCKER_HOST}
```

The above ctlptl command does not output a '\n' on the end of the output message, and I cannot find it.  This is causing me to try to remove the character in bash, which is turning out difficult

**Comment by nicks** [comment]
Thanks for the report! I'm not sure I totally follow though...

1) the missing newline is expected...it also happens with kubectl.

```
kubectl get pods -n kube-system kube-apiserver-kind-control-plane -o template --template '{{.metadata.name}}'
```

2) If there is no newline, I don't know why you'd need to remove it in bash?

3) I don't think you want to assign to DOCKER_HOST, since this is a registry url (not a docker daemon)...I suspect that's the real underlying problem...

In any case, I'll take this as a signal that we need better docs on how to get and use the registry url

**Comment by chrislovecnm** [comment]
Closing, I found my typo

**Comment by nicks** [comment]
added some more docs on this to help: https://github.com/tilt-dev/ctlptl#kind-with-a-built-in-registry-at-a-pre-determined-port
