### ISSUE TITLE
Support docker socket override or use DOCKER_HOST env var

### ISSUE THREAD

**Issue by janmonterrubio** [tilt-dev/ctlptl#196]
# Context

I'm using [colima](https://github.com/abiosoft/colima) to manage docker and not require a docker-desktop install on Mac (due to licensing).

## Problem

When `ctlptl` attemps to create a kind cluster, it uses the [dockerDesktopSocketPath](https://github.com/tilt-dev/ctlptl/blob/37bafee2633fdbaecdb896d660d06886ea016e38/pkg/cluster/docker_desktop_dial.go#L25)

```
ctlptl create cluster kind --name=kind2
could not connect to Docker Desktop. Please ensure Docker is installed and up to date.
  (caused by: Get "http://localhost/settings": dial unix /Users/USERNAME/Library/Containers/com.docker.docker/Data/backend.native.sock: connect: no such file or directory)
  ```
  
  Colima manages the docker socket at:
  
  ```
  echo $DOCKER_HOST
unix:///Users/USER/.colima/docker.sock
```

## Questions

1. Would it be possible to support either specifying the docker host OR respecting the environment variable? 

I came to the conclusion of this being a possible workaround based on this [answer regarding vscode](https://github.com/abiosoft/colima/issues/141#issuecomment-1021831220)

**Comment by nicks** [comment]
ya, it should be fairly simple to support this

you're mixing up the docker socket with the docker desktop socket, which are a little different.

i think what you need to do is change the IsLocalHost() call here:
https://github.com/tilt-dev/ctlptl/blob/ca16f2f53bc78b3ba1b74ac043554cf30f8d178a/pkg/cluster/machine.go#L93
so that if you're using the colima socket, it doesn't try to connect to docker desktop (ctlptl currently assumes that if you're connecting to a local socket, you must be connecting to docker desktop)

want to try it locally first and see if that works for you, or if you hit other issues?

**Comment by janmonterrubio** [comment]
> want to try it locally first and see if that works for you, or if you hit other issues?

Definitely, I'll try this out locally and report back. Thank you so much for pointing me in the right direction!

**Comment by janmonterrubio** [comment]
Aight, wrangling things to return not localHost worked alright. Made a PR, thanks in advance @nicks
