### ISSUE TITLE
setting up a kind cluster with docker mounted in docker

### ISSUE THREAD

**Issue by nicks** [tilt-dev/ctlptl#251]
From the tilt slack channel:

> When ctlptl applies the new cluster, it can never connect because the kubeconfig IP is set incorrectly. So it waits 5 minutes then bails. Our one working solution is to use KIND directly to create the cluster, modify the kubeconfig to point at a working IP, and then use the cluster... but then I have to write shell scripts to manage the cluster and attached temporary registry. So it would be ideal if I could use ctlptl.

I think they're using docker-socket-mounted-in-docker, which means that the cluster and registry will be in sibling containers, but the networking won't be set up right. ctlptl should detect this case and patch up the networking, similar to how we do it when there's a remote docker host.

**Comment by nicksieger** [comment]
I ran into this running kind inside a docker-out-of-docker (socket-mounted) setup when I was working on generating new screenshots for tilt docs (tilt-dev/tilt.build#1114). Not sure if [these commands are the right incantation](https://github.com/tilt-dev/tilt.build/pull/1114/files#diff-4d047ffcfaa53d824809efe1ed98d80b29d4db68784554ab4784520e26002d18R28-R30) for every situation, but they did work for what I was doing (they are in a kind wrapper script so that ctlptl would still work with waiting for the cluster to come up).

```shell
name=$(kubectl config view --minify -o jsonpath='{.clusters[0].name}')
docker network connect kind $(hostname)
kubectl config set clusters.$name.server https://${name#kind-}-control-plane:6443
```

I think the registry "just works" in the Dood case because the docker daemon is able to see and push to localhost:reg-port. So we only need to change the server name in the kubeconfig as above when ctlptl can't connect to the value in the  .clusters[0].cluster.server field of the original kubeconfig generated by kind.
